# Generated by Django 6.0.4 on 2026-04-23 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BenchmarkHire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_row_index', models.PositiveIntegerField(unique=True)),
                ('role_title', models.CharField(max_length=255)),
                ('normalized_role_title', models.CharField(db_index=True, max_length=255)),
                ('function', models.CharField(db_index=True, max_length=64)),
                ('seniority', models.CharField(blank=True, max_length=64)),
                ('cost_per_hire_usd', models.PositiveIntegerField()),
                ('cost_per_hire_display', models.CharField(max_length=16)),
                ('company_stage', models.CharField(db_index=True, max_length=32)),
                ('stage_rank', models.PositiveSmallIntegerField(db_index=True)),
                ('company_location', models.CharField(max_length=255)),
                ('normalized_city', models.CharField(blank=True, db_index=True, max_length=128)),
                ('normalized_region', models.CharField(blank=True, db_index=True, max_length=128)),
                ('geo_cluster', models.CharField(blank=True, db_index=True, max_length=64)),
                ('notable_investors', models.TextField(blank=True)),
                ('recruiter_name', models.CharField(max_length=128)),
            ],
            options={
                'ordering': ['source_row_index'],
            },
        ),
        migrations.CreateModel(
            name='RecruiterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=128)),
                ('location', models.CharField(max_length=128)),
                ('years_experience', models.PositiveSmallIntegerField()),
                ('headline', models.CharField(max_length=255)),
                ('bio', models.TextField()),
                ('functions', models.JSONField(default=list)),
                ('stage_focus', models.JSONField(default=list)),
                ('geo_focus', models.JSONField(default=list)),
                ('hiring_priority_focus', models.JSONField(default=list)),
                ('sample_role', models.CharField(max_length=255)),
                ('sample_cost_display', models.CharField(max_length=16)),
                ('sample_stage', models.CharField(max_length=32)),
                ('accent', models.CharField(default='forest', max_length=32)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
